-- phpMyAdmin SQL Dump
-- version 4.7.7
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Mar 07, 2018 at 03:41 PM
-- Server version: 5.6.38
-- PHP Version: 7.2.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `db_portal_berita`
--

-- --------------------------------------------------------

--
-- Table structure for table `tb_berita`
--

CREATE TABLE `tb_berita` (
  `id` int(11) NOT NULL,
  `foto` varchar(100) NOT NULL,
  `judul_berita` varchar(255) NOT NULL,
  `tanggal_posting` date NOT NULL,
  `isi_berita` text NOT NULL,
  `penulis` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `tb_berita`
--

INSERT INTO `tb_berita` (`id`, `foto`, `judul_berita`, `tanggal_posting`, `isi_berita`, `penulis`) VALUES
(1, 'foto_1.jpg', 'Trump Pertimbangkan Aksi Militer Baru terhadap Rezim Suriah', '2017-11-30', 'Pemerintahan Presiden Amerika Serikat Donald Trump mempertimbangkan untuk melancarkan aksi militer baru terhadap pemerintah Suriah, sebagai respons atas laporan penggunaan senjata kimia. </br></br>\r\nTrump telah meminta militer untuk mempertimbangkan opsi-opsi terhadap rezim Presiden Bashar al-Assad setelah serangan-serangan gas klorin dilaporkan terjadi di Suriah, termasuk di Ghouta Timur, dan kemungkinan serangan kimia lainnya di wilayah-wilayah yang dikuasai pemberontak. Jika dilakukan, ini akan menjadi aksi militer kedua AS terhadap rezim Suriah dalam satu tahun ini.\r\n</br></br>\r\nPemerintah Suriah telah membantah tudingan menggunakan senjata kimia dalam serangan-serangan terhadap pemberontak ataupun warga sipil. Pekan lalu, Suriah bahkan membantah tuduhan memiliki senjata kimia dan menekankan bahwa kelompok-kelompok militan yang beroperasi di negara itu, termasuk ISIS dan al-Nusra, telah memiliki sejumlah senjata kimia.\r\n</br></br>\r\nMenurut pejabat-pejabat AS seperti dilansir media The Washington Post, Rabu (7/3/2018), Trump membahas kemungkinan aksi-aksi dalam pertemuan di Gedung Putih bersama pejabat-pejabat tinggi termasuk Kepala Staf John F. Kelly, penasihat keamanan nasional H.R. McMaster dan Menteri Pertahanan Jim Mattis.\r\n</br></br>\r\nJuru bicara Departemen Pertahanan AS Dana White, membantah bahwa Mattis mendukung kemungkinan aksi militer di Suriah. Seorang pejabat senior lainnya mengatakan Mattis dengan tegas menentang aksi militer sebagai respons atas serangan-serangan klorin, sedangkan McMaster mendukung aksi militer.\r\n</br></br>\r\nSebelumnya pada April 2017 lalu, Trump memerintahkan serangan rudal ke sebuah pangkalan udara di Suriah menyusul serangan gas sarin yang menewaskan 80 orang. Itu merupakan serangan langsung Amerika terhadap pemerintah Assad.', 'Antonio Sikumbang'),
(2, 'foto_2.jpg', 'Jejak Kasus \'Raja Rampok\' Pantura yang Ditembak Mati Polisi', '2018-03-07', 'Polisi meringkus 11 orang komplotan perampok wilayah Pantura. Satu di antaranya E alias Rojak sang \'raja rampok\' Pantura ditembak mati. Komplotan ini punya catatan kriminal mentereng di Pantura.\r\n</br></br>\r\nKomplotan perampok tersebut telah malang melintang di kawasan Pantura di Cirebon, Indramayu dan Majalengka. Selain E, polisi juga menangkap 10 orang lainnya yaitu JJ (43), EAR (47), SL (38), TS (53), MY (44), AA (30), NH (37), AAN (38), S (49) dan JJD (29).\r\n</br></br>\r\n\"Ada tiga kasus yang memang ada laporan polisinya. Ketiga kasus di tempat berbeda di wilayah Pantura seperti di Cirebon, Majalengka dan Indramayu,\" ucap Wadirkrimum Polda Jabar AKBP Trunoyudho Wisnu Andiko di Rumah Sakit Sartika Asih, Jalan Moch Toha, Bandung, Rabu (7/3/2018).\r\n</br></br>\r\nKasus pertama terjadi pada Jumat (26/1) lalu. Enam dari sebelas pelaku yaitu Rojak, NH, AAN, JJD, S, dan SL merampok sebuah rumah di Desa Kalianayar, Kecamatan Panguragan, Kabupaten Cirebon.\r\n</br></br>\r\nKasus kedua terjadi di Blok Rebo Rt. 003 / 002 Desa Sindang Kecamatan Cikijing, Kabupaten Majalengka pada Kamis (15/2) lalu. Rojak ikut berperan dalam aksi di TKP tersebut. Ia bergabung dengan S, JJ dan EAR.\r\n</br></br>\r\nKasus terakhir, Rojak bersama TS, MY, dan SL merampok sebuah toko di Blok Prapatan RT. 011 RW. 002, Desa Kertilaca, Kecamatan Tukdana, Kabupaten Indramayu.\r\n</br></br>\r\n\"Semua tiga TKP ini modusnya sama dengan cara congkel, masuk rumah dan terhadap korban dilakukan penyekapan lakban serta harta benda dalam rumah dikuras untuk dikuasai,\" kata dia.\r\nKini sepuluh rekan Rojak sudah ditahan polisi. Mereka dijerat Pasal 365 KUHPidana dengan ancaman di atas 7 tahun bui.', 'Yahya Matana'),
(3, 'foto_3.jpg', 'Imbas Muatan Truk Tumpah, Lalin Tol Dalam Kota hingga Cikampek Macet', '2018-03-07', 'Lalu lintas di Tol Cikampek terpantau padat. Kepadatan kendaraan disebabkan imbas truk yang muatannya tumpah ke badan jalan.\r\n</br></br>\r\n\"Tadi ada evakuasi kendaraan truk yang bawa besi berbobot 8 ton di KM 38+450. Tali sling terputus sehingga muatan jatuh ke jalan. Saat ini kendaraan sudah dibawa ke rest area km 41. Saat ini jalur sudah terbuka,\" kata petugas call center PT Jasa Marga, Lala, saat dihubungi, Rabu (7/3/2018).\r\n</br></br>\r\nLala mengatakan kondisi lalu lintas sudah berangsur lancar sedikit demi sedikit. Sementara untuk arah sebaliknya lalu lintas terpantau relatif lancar.\r\n</br></br>\r\n\"Lalu lintas tersendat di Cikarang Utama karena peningkatan volume kendaraan. Kepadatan hanya sampai Cibitung saja,\" tuturnya.\r\n</br></br>\r\nSementara itu, kondisi lalu lintas di Tol Dalam Kota. Kepadatan kendaraan juga disebabkan peningkatan volume kendaraan.\r\n</br></br>\r\n\"Untuk kondisi di Tol Dalam Kota terjadi kepadatan di Jelambar sampai Cawang. Kepadatan lalu menyambunng di Cawang mengarah Cikarang Pusat atau kawasan Deltamas,\" ucap Lala.\r\n</br></br>\r\nSedangkan kondisi lalu lintas di Tol Lingkar Luar (JORR), kepadatan juga terjadi di ruas jalan Pondok Indah menuju Taman Mini Indonesia Indah (TMII). Kepadatan lalu lintas tersebut menyambung hingga ke arah Tol Cikampek, tepatnya di daerah Cikunir.\r\n</br></br>\r\n\"Untuk di Tol JORR, padatnya dari Pondok Indah sampai Cikunir. Kepadatan karena imbas kendaraan ke arah Cikampek atau Cikarang Pusat. Untuk arah sebaliknya, kondisi menuju Cikarang Utama kondisi relatif lancar sampai Ulujami,\" ujar Lala.\r\nKepadatan di Tol JORR tersebut terjadi sepanjang 5-10 kilometer. \"Panjangnya kurang lebih 5-10 km,\" kata dia. ', 'Made Irawan\r\n'),
(4, 'foto_4.jpg', 'Babi Hutan Nyelonong Masuk Masjid, Lukai Jemaah Salat Maghrib', '2018-03-07', 'Jamaah salat Maghrib di Masjid Jamek Sungai Plong, Selangor, Malaysia terganggu karena adanya babi hutan yang masuk ke dalam masjid. Hewan berkaki empat itu merangsek masuk dan melukai seorang jemaah.\r\n</br></br>\r\nDilansir dari media Malaysia The Star, Rabu (7/3/2018), peristiwa ini terjadi di Sungai Buloh, Malaysia, Selasa (6/3) waktu setempat. \r\n</br></br>\r\nImam Masjid bernama Ungku Ahmad Hazwan Ungku Kamarudin mengatakan peristiwa ini terjadi saat para jamaah selesai melakukan salat Maghrib. Sebagian jamaah sedang menunaikan salat sunah ba\'diyah.\r\n</br></br>\r\n\"Masjid kami didatangi oleh babi hutan yang tersesat di lantai masjid,\" kata Ungku Ahmad.\"Kemudian babi itu mengejar jemaah masjid dan anak-anak. Babi itu masuk masjid dan kami bisa melihat babi itu dan lehernya terluka,\" kata dia.\r\n</br></br>\r\nPara jamaah berusaha menghalau hewan berkaki empat itu agar keluar dari area ibadah. \"Seseorang terluka oleh hewan itu. Beberapa orang terlihat berusaha ke luar ruangan dan berusaha mengusir babi itu dari masjid,\" kata Imam di akun Facebook-nya.', 'Ihkwan Dede'),
(5, 'foto_5.jpg', 'Jokowi Terima PSI Cs di Istana Dikritik, Moeldoko: Semua Lagi Baper\r\nGibran Maulana Ibrahim - detikNews', '2018-02-28', 'Pertemuan Presiden Joko Widodo dengan sejumlah partai baru seperti PSI dan Perindo dikritik. Kepala Staf Kepresidenan Moeldoko menganggap pihak yang mengkritik Jokowi terlalu membawa perasaan atau baper.\r\n</br></br>\r\n\"(Pertemuan) Bisa di mana saja, kebetulan di Istana. Karena semua ini sekarang sedang baper,\" ujar Moeldoko dalam acara Mata Najwa, Rabu (7/3/2018).\r\n</br></br>\r\nKetua DPP PKS Mardani Ali Sera sangat tak setuju dengan pertemuan tersebut. Menurutnya, fasilitas negara tak boleh dipakai untuk kepentingan politik praktis seorang pribadi,\"Politik praktis itu terlarang dilakukan di fasilitas negara,\" kata Mardani.\r\n</br></br>\r\nKetua DPP Gerindra Ahmad Riza Patria menyuarakan hal serupa dengan Mardani. Bagi Riza, Jokowi seolah lupa dengan ucapannya yang mengatakan pejabat negara jangan terlibat politik aktif,\r\n\"Presiden berkali-kali bilang pejabat negara jangan terlibat aktif. Rupanya lupa,\" sindir Riza.', 'Selamet Riyadh'),
(6, 'foto_6.jpg', 'Aset Nazaruddin Rp 12,4 M akan Dihibahkan KPK ke Polri', '2018-03-01', 'KPK akan menghibahkan rampasan aset dari mantan Bendahara Umum Partai Demokrat Muhammad Nazaruddin dan mantan Bupati Bangkalan Fuad Amin. Aset tersebut rencananya diberikan kepada Polri. \r\n</br></br>\r\n\"Besok (8/3), sebagai bagian dari agenda Rakernis Bareskrim 2018 di Hotel Mecure, Ancol, direncanakan akan dilakukan penyerahan barang rampasan dari kasus Nazaruddin dan Fuad Amin,\" ucap Kabiro Humas KPK Febri Diansyah kepada wartawan, Rabu (7/3/2018).\r\n</br></br>\r\nFebri menyebut aset Nazaruddin yang akan dihibahkan berupa dua bidang tanah dan bangunan di Jakarta Selatan. Aset itu akan dihibahkan untuk digunakan Bareskrim Polri mendukung pelaksanaan tugas penegakan hukum.\r\n</br></br>\r\n\"(Dari) perkara Nazaruddin berupa dua bidang tanah dan bangunan seharga Rp 12,4 miliar yang bertempat di Jalan Wijaya Graha Puri Blok C No 15 Kelurahan Pulo, Kecamatan Kebayoran Baru, Jakarta Selatan,\" tutur Febri.\r\n</br></br>\r\nSementara itu, dari perkara Fuad Amin, aset yang akan dihibahkan adalah sebuah unit mobil bertipe Kijang Innova XW43 tahun 2010, yang menurut Febri akan digunakan oleh Polres Tana Toraja. Hibah barang milik negara ini dilakukan sesuai dengan Keputusan Menteri Keuangan.\r\n</br></br>\r\nFebri menyebut rencana penyerahan hibah besok juga akan dihadiri oleh pimpinan KPK. \"Direncanakan ada pimpinan besok yang akan hadir dalam penyerahan,\" ujar Febri.\r\n</br></br>\r\nNazaruddin dihukum 6 tahun penjara dan denda Rp 1 miliar. Dia terbukti melakukan TPPU dalam kasus suap wisma atlet. Hakim juga memutuskan merampas harta Nazaruddin untuk negara dengan total Rp 500-an miliar.\r\n</br></br>\r\nSelain itu, majelis mengabulkan perampasan sejumlah aset Nazaruddin untuk negara dan di antaranya telah dihibahkan ke negara, seperti tanah dan bangunan di Pancoran, Jakarta Selatan, senilai Rp 24,5 miliar yang diserahkan ke ANRI. Ada pula aset yang dilelang, seperti beberapa mobil dan pabrik kelapa sawit di Kampar, Riau, yang laku sekitar Rp 40 miliar. Namun ada juga beberapa aset Nazar yang akhirnya dikembalikan kepadanya.\r\n</br></br>\r\nSedangkan Fuad Amin dihukum 13 tahun penjara. Selain itu, aset Fuad senilai Rp 414 miliar dirampas. Fuad terbukti melakukan korupsi APBD lebih dari Rp 300 miliar, menerima suap dari PT MKS lebih dari Rp 18 miliar, dan jual-beli jabatan lebih dari Rp 20 miliar. ', 'Asadullah Elhamsey'),
(7, 'foto_7.jpg', 'KPK Cek soal Aliran Duit dari 2 KPK Cek soal Aliran Duit dari 2 Tersangka Kasus e-KTP ke Novanto', '2018-03-07', 'Penyidik KPK melakukan cek silang keterangan Setya Novanto berkaitan dengan aliran uang proyek e-KTP yang diduga mengalir padanya. Aliran uang pada Novanto itu diduga melewati 2 orang tersangka baru perkara tersebut yaitu Irvanto Hendra Pambudi Cahyo dan Made Oka Masagung.\r\n</br></br>\r\n\"IHP (Irvanto Hendra Pambudi Cahyo) dan MOM (Made Oka Masagung) memang 2 orang yang kami duga sebagai pihak perantara proses perpindahan uang atau penerimaan uang yang diduga diterima oleh SN (Setya Novanto). Karena itu keterkaitannya cukup dekat sehingga kita tentu perlu mengklarifikasi beberapa hal di sana,\" ucap Kabiro Humas KPK Febri Diansyah di kantornya, Jalan Kuningan Persada, Jakarta Selatan, Rabu (7/3/2018).\r\n</br></br>\r\nNovanto memang hari ini diperiksa sebagai saksi untuk kedua tersangka tersebut. Menurut Febri, keterangan Novanto penting karena dianggap mengetahui peristiwa aliran uang tersebut.\r\n</br></br>\r\n\"Karena SN kami pandang mengetahui beberapa peristiwa mulai dari awal saat itu sampai pada proses koordinasi misalnya dengan Sugiharto atau dengan pihak-pihak lain termasuk Andi Agustinus dan yang sudah kita proses juga,\" kata Febri.\r\n</br></br>\r\nMenurut Febri, sebenarnya berkaitan dengan aliran uang itu sudah muncul dalam persidangan Novanto. Namun, fakta-fakta persidangan itu masih perlu dicek silang pada Novanto.\r\n</br></br>\r\n\"Karena sejak dakwaan Setya Novanto kita sudah menyebut bahwa Setya Novanto diduga menerima USD 7,3 juta melalui 2 orang ini dengan berbagai cara, termasuk menggunakan beberapa terobosan dalam sistem keuangan, tidak hanya di Indonesia, tapi di beberapa negara di dunia,\" ujar Febri.\r\n</br></br>\r\nIrvanto merupakan keponakan Novanto yang dijerat KPK diduga mengetahui ada permintaan fee 5 persen untuk mempermudah proses pengurusan anggaran e-KTP. KPK menduga Irvanto kemudian menerima uang sejumlah total USD 3,5 juta, yang disebut ditujukan untuk Novanto.\r\n</br></br>\r\nSementara itu, peran Made Oka disebut KPK dengan menampung uang untuk Novanto senilai total USD 3,8 juta. Perinciannya, lewat OEM Investment Pte Ltd Singapura menerima uang USD 1,8 juta dari Biomof Mauritius dan rekening PT Delta Energi sebesar USD 2 juta. Selain itu, Made Oka merupakan perantara jatah komisi untuk anggota DPR sebesar 5 persen dari proyek e-KTP. ', 'Rifqi Daniel'),
(8, 'foto_8.jpg', 'PBB Curigai Aksi Genosida Terjadi terhadap Rohingya di Myanmar\r\n', '2018-03-04', 'Perserikatan Bangsa-Bangsa (PBB) mencurigai adanya praktik genosida terhadap Rohingya di Rakhine, Myanmar sejak Agustus 2017. Ini menjadi komentar terbaru PBB setelah sebelumnya menyebut praktik pembersihan etnis masih terus berlangsung terhadap Rohingya.\r\n</br></br>\r\n\"Para korban melaporkan pembunuhan, pemerkosaan, penyiksaan dan penculikan oleh pasukan keamanan dan milisi lokal, yang diduga upaya sengaja untuk memaksa Rohingya meninggalkan area itu melalui kelaparan, dengan para pejabat memblokir akses pada panen dan suplai makanan,\" sebut Komisioner Tinggi HAM pada PBB, Zeid Ra\'ad al-Hussein, dalam pidato di hadapan Dewan HAM PBB, seperti dilansir Reuters, Rabu (7/3/2018).\r\n</br></br>\r\n\"Dewan (HAM) ini menyadari bahwa kantor saya memiliki kecurigaan kuat bahwa aksi genosida mungkin telah terjadi di Rakhine State sejak Agustus (2017),\" tegas Zeid dalam pidatonya di Jenewa, Swiss. \r\n</br></br>\r\nDalam pidatonya, Zeid juga menyinggung laporan-laporan pembuldoseran di lokasi yang diduga kuburan massal Rohingya. \"Menunjukkan upaya sengaja oleh otoritas (Myanmar) untuk menghancurkan bukti dugaan kejahatan internasional, termasuk dugaan kejahatan kemanusiaan,\" sebutnya. \r\n</br></br>\r\nNyaris 700 ribu warga Rohingya melarikan diri ke Bangladesh sejak operasi militer Myanmar marak pada Agustus 2017. Mereka bergabung dengan 200 ribu pengungsi Rohingya yang lebih dulu mengungsi karena berbagai konflik sektarian terdahulu. Zeid menyatakan kantornya menerima laporan soal tanah-tanah yang sebelumnya dihuni Rohingya, kini diambil alih dan anggota kelompok etnis lainnya dibiarkan tinggal di sana. \r\n</br></br>\r\n\"Pengumuman terbaru bahwa tujuh tentara dan tiga pejabat kepolisian akan diadili untuk dugaan pembunuhan di luar hukum terhadap 10 pria Rohingya jelas tidak cukup,\" ucapnya. \r\n</br></br>\r\nDitegaskan Zeid bahwa pemerintah Myanmar harus mengambil tindakan nyata untuk sungguh-sungguh bertanggung jawab atas pelanggaran HAM terhadap Rohingya, termasuk soal status kewarganegaraan. \r\n</br></br>\r\nBelum ada komentar dari pemerintah Myanmar terhadap pernyataan Zeid ini. Di dalam forum Dewan HAM PBB, delegasi Myanmar diperbolehkan memberikan tanggapan pada Kamis (7/3) besok. \r\n</br></br>\r\nDalam pernyataan terpisah pada Selasa (6/3) waktu setempat, Zeid juga menyatakan keyakinannya bahwa praktik pembersihan etnis terhadap Rohingya masih terus berlangsung di Rakhine. Disebutkan Zeid bahwa Rohingya masih melarikan diri karena praktik kekerasan dan persekusi, meskipun intensitasnya lebih rendah namun sistematis, masih terjadi.', 'Tuan Turun Saika');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `tb_berita`
--
ALTER TABLE `tb_berita`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `tb_berita`
--
ALTER TABLE `tb_berita`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
